### ISSUE TITLE
Hide touchbar when keyboard is active

### ISSUE THREAD

**Issue by tekyman007** [LaughingQuoll/TouchBar#14]
It's difficult to tape quickly on the keyboard without hitting the touchbar accidentally.

**Comment by LaughingQuoll** [comment]
It cannot be hidden, how about require a double tap for any buttons when the keyboard is active? Or outright disable it while keyboard is shown?

**Comment by tekyman007** [comment]
Yes, double click is a nice solution !
Offering both solutions in preferences is ever better
Thanks

**Comment by LaughingQuoll** [comment]
I'll include this in Version 1.3
