### ISSUE TITLE
Can't rotate screen when using TouchBar

### ISSUE THREAD

**Issue by ilyan30f** [LaughingQuoll/TouchBar#2]
Unable to rotate screen for photos, videos or youtube with TouchBar enabled.

**Comment by LaughingQuoll** [comment]
iOS Version and Device please.

**Comment by LaughingQuoll** [comment]
And do you by any chance have rotation lock enabled?

**Comment by ilyan30f** [comment]
iPhone 6s - iOS 10.1.1
Triple checked for rotation lock.

**Comment by LaughingQuoll** [comment]
Thank you. Cannot replicate, can you disable all other tweaks to check that is it, Also what height do you have set for TouchBar?

**Comment by ilyan30f** [comment]
I'll try. The height is 40.00

**Comment by LaughingQuoll** [comment]
I looked into this, cannot recreate, have added some code that should fix this.
