### ISSUE TITLE
TouchBar UI issue on Phone.app

### ISSUE THREAD

**Issue by ilyan30f** [LaughingQuoll/TouchBar#20]
It moves everything up, not centered.
Currently disabled on this app.
![img_2198](https://cloud.githubusercontent.com/assets/10600018/26763531/84a63906-4922-11e7-8095-1f04ce8693a7.PNG)

**Comment by LaughingQuoll** [comment]
Doesn't loop like an issue, can you show me what it looks like without touchbar, Thanks.

**Comment by ilyan30f** [comment]
Here you go.
![img_2200](https://cloud.githubusercontent.com/assets/10600018/26766428/abfcca00-495f-11e7-8dfd-193f945da0f5.PNG)

**Comment by LaughingQuoll** [comment]
Ok thank you for this.
