### ISSUE TITLE
Installation conflicts with cercube

### ISSUE THREAD

**Issue by J-Peezy** [LaughingQuoll/TouchBar#21]
I need cercube so I haven't installed it, but it conflicts with cercube, On Cydia, I can't install it without removing cercube, and I don't want to do that
![img_2397](https://cloud.githubusercontent.com/assets/29179328/26763736/f83c73c6-494f-11e7-88d5-56ae112ed842.PNG)

**Comment by J-Peezy** [comment]
On Cydia, I can't install it without removing cercube, and I don't want to do that

**Comment by LaughingQuoll** [comment]
Currently causes a respring loop, this is a known issue and I am working with the developer to resolve this.
