### ISSUE TITLE
Quick reply is ruined

### ISSUE THREAD

**Issue by Mvrcu** [LaughingQuoll/TouchBar#22]
When using touch bar and disabling it for messages it works fine in message apps but in Quick reply it simply leaves a blank space where touchbar should be. iOS 10.2 iPhone 6s

**Comment by LaughingQuoll** [comment]
Can you please attach a screenshot, Thanks.

**Comment by Mvrcu** [comment]
http://imgur.com/4mgPGEH
Here you go.

**Comment by LaughingQuoll** [comment]
Thank you.

**Comment by LaughingQuoll** [comment]
Will fix this in 1.3
