### ISSUE TITLE
CC, NC and all activator action stoped working after 2 days

### ISSUE THREAD

**Issue by tekyman007** [LaughingQuoll/TouchBar#26]
Respering and reboot doesn't resolve the problem.
I had to uninstall touchbar.
iPhone 7

**Comment by LaughingQuoll** [comment]
Does it work again with TouchBar removed?

**Comment by tekyman007** [comment]
Yes

**Comment by LaughingQuoll** [comment]
Cannot replicate, nor has anyone else reported this, please disable all other tweaks and see if it is a clash.
