### ISSUE TITLE
Not compatible with QRC for WA 

### ISSUE THREAD

**Issue by ilyan30f** [LaughingQuoll/TouchBar#28]
When using QRC for WA on lock screen (TouchBar disabled on lock screen) or in NC (TouchBar disabled on Homescreen) there is a blank space where TouchBar should be, and the text area disappears (so I can't see what I'm writing). 
![b final](https://user-images.githubusercontent.com/10600018/27015440-abecbe36-4edb-11e7-87d9-52628872c943.png)

**Comment by LaughingQuoll** [comment]
I'll see what I can do, I may not be able to fix this.
