### ISSUE TITLE
Resolution issue where dock is too close to the upper row of icons

### ISSUE THREAD

**Issue by ilyan30f** [LaughingQuoll/TouchBar#3]
This might be an issue with LittleBrother (6+/6s+ resolution on 6s) where the dock is too close to the upper row, so there is no space for labels or page dots.
![fullsizerender](https://cloud.githubusercontent.com/assets/10600018/26760404/fb916ec0-48e4-11e7-8a38-f1dc32b588aa.jpg)

**Comment by LaughingQuoll** [comment]
Thank you for this. Does adjusting the touchbar height partially solve this?

**Comment by ilyan30f** [comment]
Nope. Adjusted the height to 20 (Previously 40) 
![img_2197](https://cloud.githubusercontent.com/assets/10600018/26763255/c1e6c4fc-491d-11e7-8913-a00c857ec692.PNG)

**Comment by LaughingQuoll** [comment]
Fixed as of 1.2 which will go out on Sunday.
