### ISSUE TITLE
Issue with QRC for WhatsApp

### ISSUE THREAD

**Issue by t1me2die** [LaughingQuoll/TouchBar#7]
If I open QRC for WhatsApp the Touchbar Overlay the QRC Window and I cant see my text with I type.

**Comment by LaughingQuoll** [comment]
Hello,

Due to how the applications are being resized some ignore this and stay full size. Until I can find a better method to resolve this, you can disable the application via the touchbar settings.

Sorry for any inconvenience.

**Comment by t1me2die** [comment]
Hi, thanks for your quick reply, but I cant disable TouchBar for QRC for WhatsApp. Its an tweak which I cant select under "Disable in Application". If I disable it for WhatsApp nothing changed
